name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build, Lint, Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Show versions
        run: |
          rustc -Vv
          cargo -V

      - name: Format check
        run: bash .ci/fmt.sh

      - name: Build (all targets)
        run: cargo build --workspace --all-targets --verbose

      - name: Clippy (allow warnings for now)
        run: bash .ci/clippy.sh

      - name: Test
        run: bash .ci/test.sh
